# Generated by Django 4.2.7 on 2025-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('skills_required', models.TextField(help_text='Comma-separated skills')),
                ('job_type', models.CharField(max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('posted_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
