# Generated by Django 4.2.7 on 2025-10-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('coursera', 'Coursera'), ('udemy', 'Udemy'), ('youtube', 'YouTube')], default='internal', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True),
        ),
    ]
